version: "3.8"
services:
  node:
      build: .
      ports:
        - 3002:3002
      volumes:
        - ./:/usr/src/app
      depends_on:
        - mysql-server
  mysql-server:
      image: mysql:5.7
      ports:
        - 3300:3300
      environment:
        MYSQL_ROOT_PASSWORD: root
        DB_NAME: test
        DB_USER: root
        DB_PASSWORD: password
      volumes:
        - data-db:/var/lib/mysql
volumes:
  data-db: {}