version: "3.8"
services:
  node:
    build: .
    ports:
      - 3002:3002
    volumes:
      - ./:/usr/src/app
      - usr/src/app/node_modules/
    depends_on:
      - mysql-server
  mysql-server:
    image: mysql:5.7
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: password
      DATABASE_NAME: vest
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
    volumes:
      - data-db:/var/lib/mysql

volumes:
  data-db: {}